server:
  address: 0.0.0.0:8080
  debug: true
  log: true
  server: "time-counter"
  interval: 10
  cors: "*"

redis:
  address: 127.0.0.1:6379
  password:
  database: 1
  prefix: tc
  maxIdle: 10
  maxActive: 500

room:
  whitelist:
    - "room1"
    - "room2"
    - "room3"